# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 504ab5c484b7566e18a1fe07db9098c689c780b3a0f349adf9989d7820f47c139d2210ef2a86f897449e3777bb577315d1090466854eb9514b5c4f1a07568d3d

test:
  secret_key_base: 148e1a1e937ace7317025770d2c3ae8f5a281a912118e97ead45a2a015c43cfb5b61da6cd575904fc2bb565b559f18befe2aa02a73b528b8ff1809a54d05ecda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
